const RoomTypes = {
    LUXURY_DOUBLE_ROOM: 'LUXURY DOUBLE ROOM',
    DELUX_DOUBLE_ROOM: 'DELUX DOUBLE ROOM',
    LUXURY_SINGLE_ROOM: 'LUXURY SINGLE ROOM',
    DELUX_SINGLE_ROOM: 'DELUX SINGLE ROOM'
  };

  module.exports = RoomTypes;